#!/usr/bin/perl
# faz uma copia, guarda data e versao de arquivo

use File::Copy;

($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst)=localtime(time);
$data=sprintf("%4d%02d%02d",$year+1900,$mon+1,$mday);

copia(@ARGV) ;
exit;

sub copia {
    foreach $arq (@_) {
            chomp $arq ;
            if ($arq =~ /(\S+\/)(\S+$)/){
                  chdir $1 ;
                  $arq = $2 ;
            }
            unless ( -d "$arq.cp" )  {
              print "Criando diretório $arq.cp\n";
                     mkdir "$arq.cp", oct("0755");
            }
            if ( -d "$arq.cp" ) {
                $n = 0;

                while ( -e "$arq.cp/$arq.$data.$n" ) {
                      $n++;
                }
                print "Copiando o arquivo para -> $arq.cp/$arq.$data.$n\n";
                copy("$arq", "$arq.cp/$arq.$data.$n") or die "copy failed: $!";
                }
            }
    }